import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
// import local from 'next/font/local';
import "./globals.css";

const inter = Vazirmatn({ subsets: ["arabic"] });
// const iran = local({
//   src: [
//     {
//       path: '../../public/fonts/iranyekan.woff2',
//       weight: '800',
//     },
//   ],
//   variable: '--iran',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} `}>{children}</body>
    </html>
  );
}
